# Brazilian E-commerce Exploratory data analysis

1. olist_customers_dataset.csv：买家个人信息表格。
1. olist_order_items_dataset.csv：订单商品信息。
1. olist_order_payments_dataset.csv：订单支付信息。
1. olist_order_reviews_dataset.csv：订单评论。
1.  olist_orders_dataset.csv：订单物流信息。
1.  olist_products_dataset.csv：商品信息。
1.  olist_geolocation_dataset.csv：各个邮编代码所指地区的经纬度。
1.  olist_sellers_dataset.csv：卖家信息。
1.  product_category_name_translation.csv：商品葡萄牙语翻译英语对应格。

## **1. Data Schema( Concatenating Data)**

![](http://i.imgur.com/HRhd2Y0.png)

In [100]:
import os 
os.getcwd()

'/Users/FIonA/Downloads/Hi.com/Exercise 3 dataset'

Convert the reviews comment from portuguese to english

In [ ]:
#using google built-in transalte in google spreadsheet 
# f5 is your cell, pt= portuguese, en= english
=if(F5="",,GOOGLETRANSLATE(F5,"pt","en"))

In [15]:
#English review comment
new_order_reviews=pd.read_csv('order_reviews.csv')
new_order_reviews.head(5)

/Users/FIonA/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,review_id,order_id,review_score,review_comment_title_pt,review_comment_title,review_comment_message_pt,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,\n,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,NaN,Recebi bem antes do prazo estipulado.,I received well before the stipulated deadline.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,NaN,Parabéns lojas lannister adorei comprar pela Internet seguro e prático Parabéns a todos feliz Pá...,Congratulations LANNISTER stores I loved to buy for the internet safe and practical Congratulati...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [16]:
new=new_order_reviews.drop(['review_comment_title_pt','review_comment_title','review_comment_message_pt'],axis=1)
new.head(5)

,review_id,order_id,review_score,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,I received well before the stipulated deadline.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,Congratulations LANNISTER stores I loved to buy for the internet safe and practical Congratulati...,2018-03-01 00:00:00,2018-03-02 10:26:53

Remove stopwords and punctuation and hyperlink

In [17]:
def re_breakline(text_list):
    """
    Args:
    ----------
    text_list: list object with text content to be prepared [type: list]
    """
    
    # Applying regex
    return [re.sub('[\n\r]', ' ', r) for r in text_list]

In [18]:
def re_hiperlinks(text_list):
    """
    Args:
    ----------
    text_list: list object with text content to be prepared [type: list]
    """
    
    # Applying regex
    pattern = 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
    return [re.sub(pattern, ' link ', r) for r in text_list]

In [19]:
import re

In [20]:
new['review_comment_message']=new['review_comment_message'].apply(str)

In [21]:
new['review_comment_message']=new['review_comment_message'].apply(lambda x:re.sub('[\n\r]', ' ', x) if x!=None else x)

In [22]:
new['review_comment_message']=new['review_comment_message'].apply(lambda x:re.sub('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', 'link', x) if x!=None else x)

In [23]:
import string
def remove_punctuations(text):
    for punctuation in string.punctuation:
        text = text.replace(punctuation, '')
    return text

In [24]:
new['review_comment_message']=new['review_comment_message'].apply(lambda x: remove_punctuations(x) if x!=None else x)

In [30]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
pat = r'\b(?:{})\b'.format('|'.join(stop))
new['tweet_without_stopwords'] = new['review_comment_message'].str.replace(pat, '')
new['tweet_without_stopwords'] = new['tweet_without_stopwords'].str.replace(r'\s+', ' ')

<ipython-input-30-d01702144ffe>:4: FutureWarning: The default value of regex will change from True to False in a future version.
  new['tweet_without_stopwords'] = new['review_comment_message'].str.replace(pat, '')
<ipython-input-30-d01702144ffe>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  new['tweet_without_stopwords'] = new['tweet_without_stopwords'].str.replace(r'\s+', ' ')

In [31]:
new.tail(5)

,review_id,order_id,review_score,review_comment_message,review_creation_date,review_answer_timestamp,tweet_without_stopwords
99995,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,nan,2017-12-09 00:00:00,2017-12-11 20:06:42,nan
99996,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,Excellent backpack super fast delivery Super recommend this store,2018-03-22 00:00:00,2018-03-23 09:10:43,Excellent backpack super fast delivery Super recommend store
99997,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,nan,2018-07-01 00:00:00,2018-07-02 12:59:13,nan
99998,be360f18f5df1e0541061c87021e6d93,f8bd3f2000c28c5342fedeb5e50f2e75,1,I requested the purchase of a Celtic Prism Meriva rear view cloak left side but arrived for m...,2017-12-15 00:00:00,2017-12-16 01:29:43,I requested purchase Celtic Prism Meriva rear view cloak left side arrived cover right side anot...
99999,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,My product arrived and I already have to return because it is defective do not hold load,2017-07-03 00:00:00,2017-07-03 21:01:49,My product arrived I already return defective hold load

In [32]:
new=new.drop(['review_comment_message'],axis=1)

In [33]:
new.head()

,review_id,order_id,review_score,review_creation_date,review_answer_timestamp,tweet_without_stopwords
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,2018-01-18 00:00:00,2018-01-18 21:46:59,nan
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,2018-03-10 00:00:00,2018-03-11 03:05:13,nan
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,2018-02-17 00:00:00,2018-02-18 14:36:24,nan
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,2017-04-21 00:00:00,2017-04-21 22:02:06,I received well stipulated deadline
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,2018-03-01 00:00:00,2018-03-02 10:26:53,Congratulations LANNISTER stores I loved buy internet safe practical Congratulations happy Easter

In [121]:
df_orders_items=pd.read_csv('update/df_orders_items')
df_merge=df_orders_items.merge(new,how='left',on='order_id')

In [128]:
df_merge.to_csv('update/orders_item_and_review',index=False)

In [134]:
df_merge.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_purchase_year,order_purchase_month,order_purchase_month_name,order_purchase_year_month,order_purchase_date,order_purchase_day,order_purchase_dayofweek,order_purchase_dayofweek_name,order_purchase_hour,order_purchase_time_day,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,id,sigla,nome,nome_regiao,review_id,review_score,tweet_without_stopwords
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,2017,10,Oct,201710,20171002,2,0,Mon,10,Morning,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,35,SP,São Paulo,Sudeste,a54f0611adc9ed256b57ede6b6eb5114,4,I test product yet came right good condition Only box came well kneaded damaged become annoying ...
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,2018,7,Jul,201807,20180724,24,1,Tue,20,Night,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,29,BA,Bahia,Nordeste,8d5266042046a06655c8db133d120ba5,4,The product good
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,2018,8,Aug,201808,20180808,8,2,Wed,8,Morning,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,52,GO,Goiás,Centro-Oeste,e73b67b67587f7644d5bd1a52deb1b01,5,nan
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,2017,11,Nov,201711,20171118,18,5,Sat,19,Night,1.0,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,24,RN,Rio Grande do Norte,Nordeste,359d03e676b3c069f62cadba8dd3f6e8,5,The product exactly I expected described site arrived well expected date
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,2018,2,Feb,201802,20180213,13,1,Tue,21,Night,1.0,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,35,SP,São Paulo,Sudeste,e50934924e227544ba8246aeb3770dd4,5,nan